// src/lib/components/blog/Search.svelte
<script lang="ts">
	import { onMount, onDestroy } from "svelte";
	import { debounce } from "lodash-es";
	import { page } from "$app/stores";
	import { goto } from "$app/navigation";
	import { fade } from "svelte/transition";

	interface SearchResult {
		id: string;
		slug: string;
		title: string;
		subtitle?: string;
		brief?: string;
		publishedAt: string;
	}

	let query = "";
	let results: SearchResult[] = [];
	let isLoading = false;
	let hasSearched = false;
	let error: string | null = null;
	let abortController: AbortController | null = null;
	let inputRef: HTMLInputElement;

	const performSearch = debounce(async (searchQuery: string) => {
		if (abortController) {
			abortController.abort();
		}

		isLoading = true;
		hasSearched = true;
		error = null;
		results = [];

		const trimmedQuery = searchQuery.trim();

		if (!trimmedQuery) {
			isLoading = false;
			return;
		}

		try {
			abortController = new AbortController();
			const searchUrl = `/api/search?q=${encodeURIComponent(trimmedQuery)}`;

			const timeoutId = setTimeout(
				() => abortController?.abort("Timeout"),
				8000
			);

			const response = await fetch(searchUrl, {
				signal: abortController.signal,
				headers: {
					"Cache-Control": "no-cache",
				},
			});

			clearTimeout(timeoutId);

			if (response.status === 304) {
				console.log("Search: Received 304 Not Modified");
				isLoading = false;
				return;
			}

			if (!response.ok) {
				let errorMsg = `Search failed: ${response.statusText}`;
				try {
					const errData = await response.json();
					errorMsg = errData.message || errData.error || errorMsg;
				} catch (_) {
					/* ignore json parsing error */
				}
				throw new Error(errorMsg);
			}

			const data = await response.json();

			if (data.error) {
				throw new Error(data.message || data.error || "Search failed.");
			}

			if (Array.isArray(data)) {
				results = data as SearchResult[];
			} else {
				console.warn("Unexpected search API response structure:", data);
				results = [];
			}
		} catch (err: any) {
			if (err.name !== "AbortError") {
				console.error("Search error:", err);
				error =
					err.message ||
					"An unexpected error occurred during search.";
				results = [];
			} else {
				console.log("Search request aborted.");
			}
		} finally {
			isLoading = false;
			abortController = null;
		}
	}, 300);

	function handleInput(e: Event) {
		const target = e.target as HTMLInputElement;
		query = target.value;
		performSearch(query);

		const url = new URL($page.url);
		if (query.trim()) {
			url.searchParams.set("q", query.trim());
		} else {
			url.searchParams.delete("q");
		}
		goto(url.toString(), {
			replaceState: true,
			keepFocus: true,
			noScroll: true,
		});
	}

	onMount(() => {
		const initialQuery = $page.url.searchParams.get("q") || "";
		query = initialQuery;
		if (initialQuery) {
			hasSearched = true;
			performSearch(initialQuery);
		}

		// Focus the search input on load
		if (inputRef) {
			setTimeout(() => inputRef.focus(), 100);
		}
	});

	onDestroy(() => {
		if (abortController) {
			abortController.abort();
		}
		performSearch.cancel();
	});

	function formatResultDate(dateString: string): string {
		try {
			return new Date(dateString).toLocaleDateString("en-GB", {
				day: "numeric",
				month: "short",
				year: "numeric",
			});
		} catch {
			return "Invalid Date";
		}
	}
</script>

<div class="w-full max-w-2xl mx-auto">
	<form on:submit|preventDefault class="mb-6 relative" role="search">
		<div class="relative">
			<input
				type="search"
				bind:value={query}
				bind:this={inputRef}
				on:input={handleInput}
				placeholder="Search posts and projects..."
				class="w-full px-4 py-3 pl-12 border border-slate-200 rounded-xl focus:ring-green-500 focus:border-green-500 transition shadow-sm text-slate-800 placeholder-slate-400"
				aria-label="Search posts and projects"
			/>
			<div
				class="absolute left-4 top-1/2 transform -translate-y-1/2 text-slate-400 pointer-events-none"
			>
				<svg
					class="w-5 h-5"
					xmlns="http://www.w3.org/2000/svg"
					fill="none"
					viewBox="0 0 24 24"
					stroke="currentColor"
				>
					<path
						stroke-linecap="round"
						stroke-linejoin="round"
						stroke-width="2"
						d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z"
					/>
				</svg>
			</div>

			{#if query && !isLoading}
				<button
					type="button"
					class="absolute right-4 top-1/2 transform -translate-y-1/2 text-slate-400 hover:text-slate-600"
					on:click={() => {
						query = "";
						results = [];
						hasSearched = false;
					}}
				>
					<span class="sr-only">Clear search</span>
					<svg
						class="w-5 h-5"
						xmlns="http://www.w3.org/2000/svg"
						fill="none"
						viewBox="0 0 24 24"
						stroke="currentColor"
					>
						<path
							stroke-linecap="round"
							stroke-linejoin="round"
							stroke-width="2"
							d="M6 18L18 6M6 6l12 12"
						/>
					</svg>
				</button>
			{/if}
		</div>
	</form>

	<div class="min-h-[300px] relative">
		{#if error}
			<div
				in:fade={{ duration: 200 }}
				class="text-center text-red-600 py-4 px-6 bg-red-50 rounded-xl border border-red-100 mb-4"
				role="alert"
			>
				<svg
					xmlns="http://www.w3.org/2000/svg"
					class="h-5 w-5 inline-block mr-1 mb-0.5"
					fill="none"
					viewBox="0 0 24 24"
					stroke="currentColor"
				>
					<path
						stroke-linecap="round"
						stroke-linejoin="round"
						stroke-width="2"
						d="M12 8v4m0 4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"
					/>
				</svg>
				<span>{error}</span>
			</div>
		{/if}

		{#if isLoading}
			<div
				in:fade={{ duration: 200 }}
				class="absolute inset-0 flex justify-center items-center bg-white/60 backdrop-blur-sm z-10 rounded-xl"
			>
				<div class="text-center">
					<div class="relative h-12 w-12 mx-auto mb-2">
						<div
							class="absolute animate-spin rounded-full h-12 w-12 border-4 border-slate-200"
						></div>
						<div
							class="absolute animate-spin rounded-full h-12 w-12 border-4 border-green-600 border-t-transparent"
						></div>
					</div>
					<p class="text-slate-600">Searching...</p>
				</div>
			</div>
		{/if}

		{#if !isLoading && results.length > 0}
			<div class="grid gap-4 md:grid-cols-2">
				{#each results as post, index (post.id)}
					<a
						href={`/blog/post/${post.slug}`}
						class="group flex flex-col h-full bg-white rounded-xl border border-slate-100 hover:border-green-200 hover:shadow-md transition-all duration-300 animate-fade-in-fast"
						style="animation-delay: {index * 50}ms"
						in:fade={{ duration: 300, delay: index * 50 }}
					>
						<div class="p-5 flex flex-col h-full">
							<h2
								class="text-lg font-display font-semibold text-slate-800 mb-2 group-hover:text-green-600 transition line-clamp-2"
							>
								{post.title}
							</h2>
							{#if post.subtitle || post.brief}
								<p
									class="text-slate-600 text-sm line-clamp-2 mb-3 flex-grow"
								>
									{post.subtitle || post.brief}
								</p>
							{/if}
							<div
								class="flex items-center mt-auto pt-3 border-t border-slate-100"
							>
								<div class="flex-1">
									<time
										class="text-xs text-slate-500"
										datetime={post.publishedAt}
									>
										{formatResultDate(post.publishedAt)}
									</time>
								</div>
								<span
									class="text-green-600 flex items-center text-xs font-medium group-hover:text-green-700 transition"
								>
									View post
									<svg
										class="ml-1 w-3.5 h-3.5 transition transform group-hover:translate-x-0.5"
										xmlns="http://www.w3.org/2000/svg"
										fill="none"
										viewBox="0 0 24 24"
										stroke="currentColor"
									>
										<path
											stroke-linecap="round"
											stroke-linejoin="round"
											stroke-width="2"
											d="M14 5l7 7m0 0l-7 7m7-7H3"
										/>
									</svg>
								</span>
							</div>
						</div>
					</a>
				{/each}
			</div>
		{:else if !isLoading && hasSearched && query.trim()}
			<div
				in:fade={{ duration: 200 }}
				class="text-center py-12 bg-slate-50 rounded-xl border border-slate-100"
			>
				<svg
					xmlns="http://www.w3.org/2000/svg"
					class="h-16 w-16 mx-auto mb-4 text-slate-300"
					fill="none"
					viewBox="0 0 24 24"
					stroke="currentColor"
				>
					<path
						stroke-linecap="round"
						stroke-linejoin="round"
						stroke-width="1.5"
						d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z"
					/>
				</svg>
				<p class="text-slate-700 text-lg font-medium mb-1">
					No results found
				</p>
				<p class="text-slate-500 text-sm max-w-md mx-auto">
					Try different keywords, check spelling, or consider broader
					terms
				</p>
			</div>
		{:else if !isLoading && !hasSearched}
			<div
				in:fade={{ duration: 200 }}
				class="text-center py-12 bg-green-50 rounded-xl border border-green-100"
			>
				<svg
					xmlns="http://www.w3.org/2000/svg"
					class="h-16 w-16 mx-auto mb-4 text-green-300"
					fill="none"
					viewBox="0 0 24 24"
					stroke="currentColor"
				>
					<path
						stroke-linecap="round"
						stroke-linejoin="round"
						stroke-width="1.5"
						d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z"
					/>
				</svg>
				<p class="text-slate-800 text-lg font-medium mb-1">
					Looking for something?
				</p>
				<p class="text-slate-600 text-sm max-w-md mx-auto">
					Type above to search through blog posts, projects, and more
				</p>
			</div>
		{/if}
	</div>
</div>

// src/components/search/Search.tsx
import { useState, useEffect, useCallback, useRef } from "react";
import { MagnifyingGlassIcon } from "@heroicons/react/24/outline";
import debounce from "lodash/debounce";
import type { HashnodePost } from "@/types/hashnode";

export default function Search() {
	const [query, setQuery] = useState("");
	const [results, setResults] = useState<HashnodePost[]>([]);
	const [isLoading, setIsLoading] = useState(false);
	const [hasSearched, setHasSearched] = useState(false);
	const [error, setError] = useState<string | null>(null);
	const abortController = useRef<AbortController | null>(null);

	useEffect(() => {
		const params = new URLSearchParams(window.location.search);
		const initialQuery = params.get("q") || "";
		setQuery(initialQuery);
		if (initialQuery) performSearch(initialQuery);

		return () => {
			abortController.current?.abort();
		};
	}, []);

	const performSearch = useCallback(
		debounce(async (searchQuery: string) => {
			abortController.current?.abort();
			setIsLoading(true);
			setHasSearched(true);
			setError(null);

			if (!searchQuery.trim()) {
				setResults([]);
				setIsLoading(false);
				return;
			}

			try {
				abortController.current = new AbortController();
				const timeoutId = setTimeout(() => {
					abortController.current?.abort();
				}, 5000);

				const response = await fetch(
					`/api/search?q=${encodeURIComponent(searchQuery)}`,
					{
						signal: abortController.current.signal,
						headers: {
							"Cache-Control": "no-cache",
							"If-None-Match":
								sessionStorage.getItem(
									`search-etag-${searchQuery}`
								) || "",
						},
					}
				);

				clearTimeout(timeoutId);

				// Handle 304 Not Modified
				if (response.status === 304) {
					const cachedResults = JSON.parse(
						sessionStorage.getItem(
							`search-results-${searchQuery}`
						) || "[]"
					);
					setResults(cachedResults);
					setIsLoading(false);
					return;
				}

				if (!response.ok)
					throw new Error(`Search failed: ${response.statusText}`);

				const etag = response.headers.get("etag");
				if (etag) {
					sessionStorage.setItem(`search-etag-${searchQuery}`, etag);
				}

				const data = await response.json();
				if (data.error)
					throw new Error(data.message || "Search failed.");

				setResults(data);
				sessionStorage.setItem(
					`search-results-${searchQuery}`,
					JSON.stringify(data)
				);
			} catch (err: any) {
				if (err.name !== "AbortError") {
					console.error("Search error:", err);
					setError(
						err instanceof Error ? err.message : "Unexpected error."
					);
					setResults([]);
				}
			} finally {
				setIsLoading(false);
			}
		}, 250),
		[]
	);

	return (
		<div className="w-full max-w-2xl mx-auto">
			<form onSubmit={(e) => e.preventDefault()} className="mb-5">
				<div className="relative">
					<input
						type="text"
						value={query}
						onChange={(e) => {
							setQuery(e.target.value);
							performSearch(e.target.value);

							// Update URL with search query
							const url = new URL(window.location.href);
							if (e.target.value) {
								url.searchParams.set("q", e.target.value);
							} else {
								url.searchParams.delete("q");
							}
							window.history.replaceState({}, "", url.toString());
						}}
						placeholder="Search posts and projects..."
						className="w-full px-4 py-2 pl-10 border border-gray-300 rounded-md focus:ring-green-600 focus:border-green-600 transition shadow-sm text-sm"
						aria-label="Search posts"
					/>
					<MagnifyingGlassIcon className="absolute left-3 top-1/2 transform -translate-y-1/2 text-gray-400 w-4 h-4" />
				</div>
			</form>
			<div className="min-h-[200px]">
				{error && (
					<div
						className="text-center text-red-500 py-3 bg-red-50 rounded-md border border-red-100 mb-4 text-sm"
						role="alert"
					>
						<p>{error}</p>
					</div>
				)}

				{isLoading ? (
					<div className="flex justify-center items-center h-48">
						<div className="text-center">
							<div className="inline-block h-8 w-8 animate-spin rounded-full border-4 border-solid border-green-600 border-r-transparent align-[-0.125em] motion-reduce:animate-[spin_1.5s_linear_infinite] mb-3"></div>
							<p className="text-gray-600">Searching...</p>
						</div>
					</div>
				) : results.length > 0 ? (
					<div className="grid gap-4 md:grid-cols-2">
						{results.map((post, index) => (
							<a
								key={post.id}
								href={`/post/${post.slug}`}
								className="group flex flex-col h-full bg-white rounded-lg border border-gray-200 hover:border-green-300 hover:shadow-sm transition"
								style={{ animationDelay: `${index * 50}ms` }}
							>
								<div className="p-4 flex flex-col h-full">
									<h2 className="text-base font-display font-bold text-gray-900 mb-1.5 group-hover:text-green-700 transition">
										{post.title}
									</h2>
									<p className="text-gray-600 text-sm line-clamp-2 mb-3 flex-grow">
										{post.subtitle || post.brief}
									</p>
									<div className="flex items-center mt-auto">
										<div className="flex-1">
											<time className="text-xs text-gray-500">
												{new Date(
													post.publishedAt
												).toLocaleDateString("en-GB", {
													day: "numeric",
													month: "long",
													year: "numeric",
												})}
											</time>
										</div>
										<span className="text-green-700 flex items-center text-xs font-medium">
											View post
											<svg
												className="ml-1 w-3 h-3 transition group-hover:translate-x-0.5"
												viewBox="0 0 20 20"
												fill="currentColor"
											>
												<path
													fillRule="evenodd"
													d="M10.293 5.293a1 1 0 011.414 0l4 4a1 1 0 010 1.414l-4 4a1 1 0 01-1.414-1.414L12.586 11H5a1 1 0 110-2h7.586l-2.293-2.293a1 1 0 010-1.414z"
													clipRule="evenodd"
												/>
											</svg>
										</span>
									</div>
								</div>
							</a>
						))}
					</div>
				) : (
					hasSearched &&
					query && (
						<div className="text-center py-8 bg-gray-50 rounded-md border border-gray-200">
							<svg
								className="mx-auto h-10 w-10 text-gray-400 mb-3"
								fill="none"
								viewBox="0 0 24 24"
								stroke="currentColor"
							>
								<path
									strokeLinecap="round"
									strokeLinejoin="round"
									strokeWidth={1.5}
									d="M9.172 16.172a4 4 0 015.656 0M9 10h.01M15 10h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"
								/>
							</svg>
							<p className="text-gray-600 text-base mb-1">
								No results found
							</p>
							<p className="text-gray-500 text-sm">
								Try different keywords or check spelling
							</p>
						</div>
					)
				)}

				{!isLoading && !hasSearched && (
					<div className="text-center py-8 bg-green-50 rounded-md border border-green-100">
						<MagnifyingGlassIcon className="mx-auto h-10 w-10 text-green-600 mb-3" />
						<p className="text-gray-700 text-base mb-1">
							Looking for something?
						</p>
						<p className="text-gray-600 text-sm">
							Type above to search through blog posts and projects
						</p>
					</div>
				)}
			</div>
		</div>
	);
}
